name = "MINPACK"
uuid = "4854310b-de5a-5eb6-a2a5-c1dee2bd17f9"
authors = ["Spencer Lyon <spencerlyon2@gmail.com>"]
version = "1.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
cminpack_jll = "b792d7bf-f512-5dba-8a02-6d8084434f1d"

[compat]
LinearAlgebra = "1"
Printf = "1"
cminpack_jll = "1.3.8"
julia = "1.6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test", "Printf"]
